services:
  db:
    image: postgres:16.4
    container_name: fandomhub_db
    restart: always
    env_file:
      - ./.env
    ports:
      - 5440:5432
    volumes:
      - .data:/var/lib/postgresql

  redis:
    image: redis:7.4.0
    container_name: fandomhub_redis
    ports:
      - 6390:6379

  web:
    container_name: fandomhub_web
    build: .
    volumes:
      - .:/app
    ports:
      - "8010:8010"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  grafana:
    container_name: fandomhub_grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    container_name: fandomhub_prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

volumes:
  grafana_data:
  prometheus_data:
