name: FandomHub CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements/local.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --config .flake8

      - name: Run pytest
        run: |
          pytest -n 4 --maxfail=3 --disable-warnings
